### PR TITLE
Fix path resolution for Windows

### PR DESCRIPTION
**Pull request by carlos-kelly**
Fix path resolutions for Windows by using a combination of `normalize` and replacing single \ with double \s

### CODE REVIEW

**Comment by ryan-roemer** [comment]
I think we need a `yarn lint --fix`

**Comment by ryan-roemer** [comment]
@Dimension4 -- Can you pull this branch and see if it works for you for (now transferred) issue https://github.com/FormidableLabs/spectacle-cli/issues/39 ? Thanks!

**Review by ryan-roemer — APPROVED** [review]
LGTM once CI is green! Thanks!

**Comment by Dimension4** [comment]
@ryan-roemer can confirm, it works. Thanks a lot!

**Pull request merged**
